import axios from 'axios';
import API from './URL';
const {
  BATTLE_CREATE_POST,
  BATTLE_DELETE_PLAYER_DELETE,
  BATTLE_DELETE_TRIGGER_DELETE,
  BATTLE_FINISH_GET,
  BATTLE_INFO_GET,
  BATTLE_LIST_GET,
  BATTLE_MODIFY_PLAYER_PATCH,
  BATTLE_REGIST_PLAYER_POST,
  BATTLE_REGIST_TRIGGER_POST,
  BATTLE_SETTING_PATCH,
  BATTLE_START_GET,
  BATTLE_WEIGHT_PATCH,
} = API;
